import {Redis} from '@upstash/redis'

//https://gist.github.com/mbejda/45db05ea50e79bc42016#file-fortune-1000-company-twitter-accounts-csv


const redis = new Redis({
  url: 'https://unified-deer-31047.upstash.io',
  token: 'AXlHASQgNmM5ZGMxMWItZDY1YS00ZDEzLTgyYTAtYjYwMDE4NmUyMDk0OTY4ODU1YjQyMTY5NGQ1MjlhZmQ2MGUwNzEwMTczNzA=',
})


const companyList = [
    "Wal-Mart Stores",
    "General Motors",
    "General Electric",
    "ChevronTexaco",
    "Philip Morris",
    "American International Group",
    "American Electric Power",
    "Boeing",
    "El Paso",
    "Home Depot",
    "J.P. Morgan Chase & Co.",
    "Cardinal Health",
    "Merck",
    "State Farm Insurance Cos.",
    "Hewlett-Packard",
    "McKesson",
    "Merrill Lynch",
    "Albertson's",
    "Freddie Mac",
    "Johnson & Johnson",
    "Conoco",
    "Pfizer",
    "J.C. Penney",
    "MetLife",
    "Goldman Sachs Group",
    "Motorola",
    "Allstate",
    "TXU",
    "United Technologies",
    "Dow Chemical",
    "ConAgra",
    "PepsiCo",
    "Wells Fargo",
    "Intel",
    "Delphi",
    "Sprint",
    "New York Life Insurance",
    "E.I. du Pont de Nemours",
    "Georgia-Pacific",
    "Walt Disney",
    "Aetna",
    "Lockheed Martin",
    "Bank One Corp.",
    "TIAA-CREF",
    "Phillips Petroleum",
    "Honeywell International",
    "UnitedHealth Group",
    "Viacom",
    "Supervalu",
    "American Express",
    "Wachovia Corp.",
    "Cisco Systems",
    "CVS",
    "Lowe's",
    "Bristol-Myers Squibb",
    "Electronic Data Systems",
    "AutoNation",
    "Qwest Communications",
    "Mass. Mutual Life Insurance",
    "Cigna",
    "Sun Microsystems",
    "HCA",
    "Raytheon",
    "Xerox",
    "TRW",
    "Abbott Laboratories",
    "Northwestern Mutual",
    "Publix Super Markets",
    "Hartford Financial Services",
    "Exelon",
    "Nationwide",
    "Xcel Energy",
    "McDonald's",
    "Kimberly-Clark",
    "May Department Stores",
    "Goodyear Tire & Rubber",
    "Gap",
    "Northrop Grumman",
    "Amerada Hess",
    "Halliburton",
    "Deere",
    "Eastman Kodak",
    "Circuit City Stores",
    "Winn-Dixie Stores",
    "Avnet",
    "WellPoint Health Networks",
    "Sunoco",
    "Textron",
    "Edison International",
    "Union Pacific",
    "Waste Management",
    "Office Depot",
    "Williams",
    "Toys `R` Us",
    "Staples",
    "Computer Sciences",
    "Dana",
    "Whirlpool",
    "Humana",
    "Southern",
    "Marriott International",
    "MBNA",
    "Arrow Electronics",
    "Marsh & McLennan",
    "Public Service Enterprise Group",
    "Schering-Plough",
    "Comcast",
    "AFLAC",
    "H.J. Heinz",
    "Colgate-Palmolive",
    "Limited",
    "John Hancock Financial Services",
    "Burlington Northern Santa Fe",
    "Agilent Technologies",
    "Fluor",
    "St. Paul Cos.",
    "Principal Financial",
    "Ashland",
    "SunTrust Banks",
    "Dillard's",
    "Masco",
    "US Airways Group",
    "Genuine Parts",
    "Texas Instruments",
    "PPG Industries",
    "CSX",
    "Gillette",
    "Sempra Energy",
    "Clear Channel Communications",
    "DTE Energy",
    "Aramark",
    "Baxter International",
    "Chubb",
    "Kohl's",
    "Progressive",
    "Applied Materials",
    "Eaton",
    "Bank of New York Co.",
    "EMC",
    "General Mills",
    "Safeco",
    "PNC Financial Services Group",
    "Newell Rubbermaid",
    "Omnicom Group",
    "Oneok",
    "Avaya",
    "Unocal",
    "Navistar International",
    "Centex",
    "Fifth Third Bancorp",
    "First Data",
    "Lincoln National",
    "Gannett",
    "Corning",
    "United Auto Group",
    "Norfolk Southern",
    "Science Applications Intl.",
    "Lennar",
    "Unisys",
    "Avon Products",
    "NCR",
    "Rohm & Haas",
    "PPL",
    "Air Products & Chemicals",
    "State Street Corp.",
    "Nordstrom",
    "Medtronic",
    "Eastman Chemical",
    "Baker Hughes",
    "Pulte Homes",
    "Dollar General",
    "USA Networks",
    "Charles Schwab",
    "BJ's Wholesale Club",
    "Praxair",
    "American Family Ins. Group",
    "Ryder System",
    "CNF",
    "Barnes & Noble",
    "AutoZone",
    "RadioShack",
    "W.W. Grainger",
    "Dole Food",
    "ITT Industries",
    "KB Home",
    "McGraw-Hill",
    "OfficeMax",
    "Park Place Entertainment",
    "Sierra Pacific Resources",
    "Maytag",
    "Ameren",
    "D.R. Horton",
    "Quantum",
    "Administaff",
    "Jabil Circuit",
    "Mutual of Omaha Insurance",
    "Levi Strauss",
    "Kelly Services",
    "Cooper Industries",
    "Computer Associates Intl.",
    "Lexmark International",
    "Cox Communications",
    "Pathmark Stores",
    "Amgen",
    "MGM Mirage",
    "Echostar Communications",
    "MeadWestvaco",
    "Starwood Hotels & Resorts",
    "CDW Computer Centers",
    "York International",
    "Clorox",
    "Advanced Micro Devices",
    "Steelcase",
    "Peter Kiewit Sons'",
    "Avery Dennison",
    "Maxtor",
    "Energy East",
    "First American Corp.",
    "Ball",
    "Family Dollar Stores",
    "Big Lots",
    "Core-Mark International",
    "Shopko Stores",
    "Puget Energy",
    "Burlington Resources",
    "USG",
    "Northern Trust Corp.",
    "Aid Association for Lutherans",
    "OGE Energy",
    "Staff Leasing",
    "PepsiAmericas",
    "Anixter International",
    "C.H. Robinson Worldwide",
    "Kindred Healthcare",
    "Devon Energy",
    "Sealed Air",
    "Hilton Hotels",
    "Neiman Marcus",
    "3Com",
    "H&R Block",
    "Reebok International",
    "Trigon Healthcare",
    "Payless Shoesource",
    "TruServ",
    "United Rentals",
    "Universal Health Services",
    "Solutia",
    "Apache",
    "Lutheran Brotherhood",
    "Spherion",
    "Manor Care",
    "PolyOne",
    "Starbucks",
    "Pantry",
    "NVR",
    "Sonoco Products",
    "M & T Bank Corp.",
    "Citizens Communications",
    "Nicor",
    "AGCO",
    "Michaels Stores",
    "American Greetings",
    "Reader's Digest Association",
    "Potomac Electric Power",
    "PetsMart",
    "Alberto-Culver",
    "Sabre Holdings",
    "Mandalay Resort Group",
    "First Tennessee National Corp.",
    "Robert Half International",
    "Huntington Bancshares",
    "Burlington Coat Factory",
    "Washington Post",
    "Erie Insurance Group",
    "Wendy's International",
    "Louisiana-Pacific",
    "Ecolab",
    "BorgWarner",
    "Weatherford International",
    "Convergys",
    "Value City",
    "Kellwood",
    "Belk",
    "Analog Devices",
    "Whole Foods Market",
    "La-Z-Boy",
    "Herman Miller",
    "Budget Group",
    "BJ Services",
    "Tellabs",
    "Pep Boys-Manny, Moe & Jack",
    "Cintas",
    "Alaska Air Group",
    "Outback Steakhouse",
    "MDC Holdings",
    "CenturyTel",
    "National Semiconductor",
    "Swift Transportation",
    "CUNA Mutual Group",
    "MONY Group",
    "J.B. Hunt Transport Services",
    "Insight Enterprises",
    "Synovus Financial Corp.",
    "America West Holdings",
    "Simon Property Group",
    "New Jersey Resources",
    "Storage Technology",
    "Compuware",
    "Weis Markets",
    "Dollar Tree Stores",
    "Protective Life",
    "CBRL Group",
    "Western Digital",
    "Ingles Markets",
    "W.R. Berkley",
    "TravelCenters of America",
    "SunGard Data Systems",
    "Casey's General Stores",
    "Safeguard Scientifics",
    "Brown-Forman",
    "CH2M Hill",
    "Valspar",
    "Flowserve",
    "Compass Bancshares",
    "Fiserv",
    "Marsh Supermarkets",
    "Magellan Health Services",
    "Silicon Graphics",
    "Lubrizol",
    "Jack in the Box",
    "Worthington Industries",
    "Linens'n Things",
    "Amerco",
    "McLeodUSA",
    "Rent A Center",
    "Kennametal",
    "Beazer Homes USA",
    "Diebold",
    "Scotts Company",
    "National Oilwell",
    "Hovnanian Enterprises",
    "Southern States Coop.",
    "Paychex",
    "Harman Intl. Industries",
    "Concord EFS",
    "Cabot",
    "Energizer Holdings",
    "Xilinx",
    "Expeditors Intl of Washington",
    "Flowers Foods",
    "Quintiles Transnational",
    "PerkinElmer",
    "Jo Ann Stores",
    "Lands' End",
    "Imperial Sugar",
    "Champion Enterprises",
    "Comfort Systems USA",
    "Legg Mason",
    "Level 3 Communications",
    "RGS Energy Group",
    "Lam Research",
    "Amkor Technology",
    "Del Monte Foods",
    "Mercury General",
    "Banknorth Group",
    "BMC Software",
    "Veritas Software",
    "Arch Coal",
    "GenCorp",
    "Atmel",
    "AIMCO",
    "E.W. Scripps",
    "Symbol Technologies",
    "Atmos Energy",
    "Teradyne",
    "American Water Works",
    "CSK Auto",
    "Phillips-Van Heusen",
    "Cadence Design Systems",
    "Sports Authority",
    "Pier 1 Imports",
    "Kemet",
    "Burlington Industries",
    "Dreyer's Grand Ice Cream",
    "Stewart & Stevenson Services",
    "Southwest Gas",
    "National Rural Utilities Cooperative",
    "Trans World Entertainment",
    "American Eagle Outfitters",
    "Nvidia",
    "Gemstar-TV Guide International",
    "Abercrombie & Fitch",
    "Novellus Systems",
    "IMS Health",
    "Carpenter Technology",
    "Electronic Arts",
    "Revlon",
    "Stein Mart",
    "Hub Group",
    "Briggs & Stratton",
    "Dun & Bradstreet",
    "AnnTaylor",
    "Pacific Century Financial",
    "Deluxe",
    "Men's Wearhouse",
    "Stewart Information Services",
    "Werner Enterprises",
    "Varco International",
    "Amica Mutual Insurance",
    "Milacron",
    "Intuit",
    "Kimball International",
    "XO Communications",
    "EarthLink",
    "Ceridian",
    "Watsco",
    "Foamex International",
    "CMGI",
    "Tektronix",
    "Genzyme",
    "Genuity",
    "Georgia Gulf",
    "International Game Technology",
    "Sealy",
    "Standard Register",
    "Goody's Family Clothing",
    "Timberland",
    "American Management Systems",
    "PC Connection"
  ];

  companyList.forEach((company) => {

    const term = company.toUpperCase()

    const terms: {score: 0, member: string}[] = []

    for (let i = 0; i < term.length; i++) {
        

        terms.push({score: 0, member: term.substring(0,i)})
    }

    terms.push({score: 0, member: term + '*'})

    const populateDb = async () => {

        // @ts-expect-error
        await redis.zadd("terms", ...terms)



    }

    populateDb()


  })
  






/*
redis-cli --tls -u redis://default:968855b421694d529afd60e071017370@unified-deer-31047.upstash.io:31047
*/